### ISSUE TITLE
Austin Park Equity listing

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/Civic_Project#13]
Name:         Austin Park Equity
Description:  This is a project to help visualize and compare the distribution of parks, recreational facilities, and green spaces in Austin.
Access_at:    http://open-austin.github.io/Austin_Parks_Acreage/
Project_at:   https://github.com/open-austin/Austin_Parks_Acreage
Type:         web application
Status:       in development
Contact:      Mateo Clarke <code@mateoclarke.com>
Categories:   [ GIS, mapping, parks, inequity, green-space ]

**Comment by chip-rosenthal** [comment]
merged. thanks.
