### ISSUE TITLE
Projects from the CfAPI

### ISSUE THREAD

**Issue by ondrae** [open-austin/Civic_Project#5]
Hey @chip-rosenthal 

You want to show off some projects? Great. For reference, here is how the Brigade is doing it so far:
* [Philly](http://codeforphilly.org/projects) - PHP - You set up and maintain your own app. Has lots of extra goodies and also outputs to the CfAPI.
* [NYC](http://codeforphilly.org/projects) - MEAN - You run the app, the projects each need a civic.json file. Outputs to the CfAPI.
* [SF](http://codeforsanfrancisco.org/projects/) - jQuery - Pulls from the CfAPI.
* [GovCode](http://www.govcode.org/) - Angular and Node - Not Brigade but a good looking example.

You had some questions about the schema too. So does everybody. The Europeans want [json-ld and schema.org](https://github.com/codeforamerica/cfapi/issues/118), the White House wants [ISO standards](https://github.com/codeforamerica/cfapi/issues/144). I've got a list of clean up to do, which I've organized into [bug fixes and enhancements](https://github.com/codeforamerica/cfapi/milestones). Its all going to happen in November and December.

The `status` column will definitely get added though.

**Comment by chip-rosenthal** [comment]
Thanks for the info.
