### ISSUE TITLE
Socrata Data Portal Analytics

### ISSUE THREAD

**Issue by nghadji** [open-austin/Civic_Project#6]
Name:         Socrata Data Portal Analytics
Description:  Suite of tools for analyzing Socrata data portal site metrics and metadata. 
Access_at:    https://github.com/nghadji/Socrata-Data-Portal-Analytics
Project_at:   https://github.com/nghadji/Socrata-Data-Portal-Analytics
Type:         web application | web service | dataset
Status:       in development
Contact:      Nick Hadjigeorge <nghadjigeorge@gmail.com>
Categories:   [ Open Data]

**Comment by chip-rosenthal** [comment]
Access_at should be blank.
Type should be: desktop application

Posted here:
https://github.com/open-austin/Civic_Project/blob/master/projects/socrata-data-portal-analytics.yml
