### ISSUE TITLE
Cycle nearby should be listed.

### ISSUE THREAD

**Issue by chip-rosenthal** [open-austin/Civic_Project#9]
The Cycle Nearby app is active and should be listed.

I'll contact Jeffrey.

**Comment by AustinBlues** [comment]
Name:         Cycle Nearby Austin
Description:  Location aware map of City of Austin resources and bicycle relate police report.
Access_at:    http://cycle-nearby.open-austin.org/
Project_at:   https://github.com/AustinBlues/Good-Sect--Bad-Sect
Type:         Web application
Status:       deployed
Contact:      Jeffrey Taylor <jeff.taylor@ieee.org>
Categories:   [ bicycle ]

**Comment by chip-rosenthal** [comment]
Merged. Thank you.
